repositories:
  - name: "mocaccino-extra"
    bucket: "mocaccino-extra"
    project: "mocaccino-extra" 
    qa: true
    enabled: true
    arch: amd64
    branch: master
    buildkit: 0
    prune: false
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    squash: false
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/extra-amd64-cache"
    tree: ""
    triggered: true

    smart: false
  - name: "mocaccino-micro"
    enabled: true
    bucket: "mocaccino-micro"
    project: "mocaccino-micro" 
    branch: master
    qa: true
    buildkit: 0
    smart: false
    prune: false
    squash: false
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd
    kube: false
    imageRepository: "quay.io/mocaccinocache/micro-amd64-cache"
    tree: ""
    triggered: true
    arch: amd64
  - name: "mocaccino-extra-arm"
    enabled: false
    bucket: "mocaccino-extra-arm"
    project: "mocaccino-extra" 
    qa: true
    triggered: false
    arch: arm
    branch: master
  - name: "mocaccino-micro-arm"
    enabled: false
    bucket: "mocaccino-micro-arm"
    
    project: "mocaccino-micro" 
    branch: master
    qa: true
    triggered: false
    arch: arm
  - name: "desktop"
    bucket: "mocaccino-desktop"
    
    enabled: true
    project: "desktop" 
    qa: true
    branch: master
    arch: amd64
    buildkit: 0
    smart: true
    prune: false
    squash: false
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/desktop"
    tree: ""
    triggered: true

  - name: "kernel-repo"
    bucket: "mocaccino-kernel"
    
    qa: true
    branch: master
    project: "kernel-repo" 
    enabled: true
    arch: amd64
    prune: false
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    buildkit: 0
    smart: true
    squash: false
    queue: lxd
    kube: false
    imageRepository: "quay.io/mocaccinocache/kernel-repo-amd64-cache"
    tree: ""
    triggered: true

  - name: "portage-tree"
    bucket: "mocaccino-portage-tree"
    prune: false
    branch: master
    qa: false
    enabled: true
    arch: amd64
    project: "portage-tree" 
    buildkit: 0
    smart: false
    squash: false
    build_args: "--emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/portage-amd64-cache"
    tree: ""
    triggered: true

  - name: "musl-universe"
    bucket: "mocaccino-musl-universe"
    
    branch: master
    qa: true
    prune: false
    arch: amd64
    project: "mocaccino-musl-universe" 
    buildkit: 0
    smart: true
    squash: false
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/musl-universe-amd64-cache"
    tree: ""
    enabled: true
    triggered: true

  - name: "mocaccino-aports"
    bucket: "mocaccino-aports"
    
    project: "mocaccino-aports" 
    branch: master
    qa: true
    arch: amd64
    buildkit: 0
    smart: false
    prune: false
    squash: true
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    tree: "/"
    imageRepository: "quay.io/mocaccinocache/aports-amd64-cache"
    enabled: true
    triggered: false

  - name: "distfiles-collection"
    bucket: "mocaccino-distfiles-collection"
    
    qa: false
    branch: master
    project: "distfiles-collection" 
    arch: amd64
    prune: true
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    buildkit: 0
    smart: false
    tree: ""
    squash: false
    kube: false
    imageRepository: "quay.io/mocaccinocache/distfiles-amd64-cache"
    queue: lxd_mocaccino
    enabled: true
    triggered: true

  - name: "mocaccino-os-commons"
    bucket: "mocaccino-os-commons"
    triggered: true
    project: "os-commons" 
    branch: master
    qa: true
    arch: amd64
    buildkit: 0
    smart: false
    prune: false
    squash: false
    build_args: "--no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    tree: "/"
    imageRepository: "quay.io/mocaccinocache/os-commons-amd64-cache"
    enabled: true

  - name: "mocaccino-funtoo"
    bucket: "mocaccino-funtoo"
    
    prune: false
    branch: master
    qa: true
    enabled: true
    arch: amd64
    project: "mocaccino-funtoo"
    buildkit: 1
    smart: false
    squash: false
    build_args: "--emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/funtoo-amd64-cache"
    tree: ""
    triggered: true

  - name: "portage-dev"
    bucket: "mocaccino-portage-dev"
    prune: false
    branch: develop
    qa: false
    enabled: true
    arch: amd64
    project: "portage-tree" 
    buildkit: 0
    smart: false
    squash: false
    build_args: "--emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/portage-amd64-cache"
    tree: ""
    triggered: false

qa:
  chart: "https://github.com/mocaccinoOS/mocaccino-charty/releases/download/v0.2.9/package-smoke-0.2.3.tar.gz"
  from_repo: true
  repo: https://github.com/mocaccinoOS/mocaccino-charty
  path: testcharts/package-smoke
  luet_version: "0.9.19"
  bucket: mocaccino-qa
slack:
  channel: "mocaccino"
  enabled: true
