repositories:
  - name: "mocaccino-extra"
    bucket: "mocaccino-extra"
    project: "mocaccino-extra" 
    qa: true
    clean: false
    arch: amd64
    branch: master
    buildkit: 0
    prune: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    squash: false

    smart: false
  - name: "mocaccino-micro"
    bucket: "mocaccino-micro"
    clean: true
    project: "mocaccino-micro" 
    branch: master
    qa: true
    arch: amd64
  - name: "mocaccino-extra-arm"
    bucket: "mocaccino-extra-arm"
    project: "mocaccino-extra" 
    qa: true
    clean: false
    arch: arm
    branch: master
  - name: "mocaccino-micro-arm"
    bucket: "mocaccino-micro-arm"
    clean: false
    project: "mocaccino-micro" 
    branch: master
    qa: true
    arch: arm
  - name: "desktop"
    bucket: "mocaccino-desktop"
    clean: false
    project: "desktop" 
    qa: false
    branch: master
    arch: amd64
    buildkit: 0
    smart: false
    prune: false
    squash: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"


  - name: "kernel-repo"
    bucket: "mocaccino-kernel"
    clean: false
    qa: true
    branch: master
    project: "kernel-repo" 
    arch: amd64
    prune: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    buildkit: 0
    smart: false
    squash: false

  - name: "portage-tree"
    bucket: "mocaccino-portage-tree"
    clean: true
    prune: false
    branch: master
    qa: true
    arch: amd64
    project: "portage-tree" 
    buildkit: 0
    smart: true
    squash: false
    build_args: "--skip-if-metadata-exists=true --emoji=false --color=false --pull --only-target-package --push"

  - name: "musl-universe"
    bucket: "mocaccino-musl-universe"
    clean: true
    branch: master
    qa: true
    prune: false
    arch: amd64
    project: "mocaccino-musl-universe" 
    buildkit: 0
    smart: false
    squash: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"

  - name: "mocaccino-aports"
    bucket: "mocaccino-aports"
    clean: true
    project: "mocaccino-aports" 
    branch: master
    qa: true
    arch: amd64
    buildkit: 0
    smart: true
    prune: false
    squash: true
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"

  - name: "distfiles-collection"
    bucket: "mocaccino-distfiles-collection"
    clean: false
    qa: false
    branch: master
    project: "distfiles-collection" 
    arch: amd64
    prune: true
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    buildkit: 0
    smart: false
    squash: false

qa:
  chart: "https://github.com/mocaccinoOS/mocaccino-charty/releases/download/v0.2.9/package-smoke-0.2.3.tar.gz"
  from_repo: true
  repo: https://github.com/mocaccinoOS/mocaccino-charty
  path: testcharts/package-smoke
  luet_version: "0.9.2"
  bucket: mocaccino-qa
slack:
  channel: "mocaccino"
  enabled: true
