repositories:
  - name: "mocaccino-extra"
    bucket: "mocaccino-extra"
    project: "mocaccino-extra" 
    qa: true
    enabled: true
    clean: true
    arch: amd64
    branch: master
    buildkit: 0
    prune: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    squash: false
    queue: lxd_mocaccino
    kube: true
    imageRepository: "quay.io/mocaccinocache/extra-amd64-cache"
    tree: ""

    smart: false
  - name: "mocaccino-micro"
    enabled: true
    bucket: "mocaccino-micro"
    clean: true
    project: "mocaccino-micro" 
    branch: master
    qa: true
    buildkit: 0
    smart: false
    prune: false
    squash: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd
    kube: false
    imageRepository: "quay.io/mocaccinocache/micro-amd64-cache"
    tree: ""
    arch: amd64
  - name: "mocaccino-extra-arm"
    enabled: false
    bucket: "mocaccino-extra-arm"
    project: "mocaccino-extra" 
    qa: true
    clean: false
    arch: arm
    branch: master
  - name: "mocaccino-micro-arm"
    enabled: false
    bucket: "mocaccino-micro-arm"
    clean: false
    project: "mocaccino-micro" 
    branch: master
    qa: true
    arch: arm
  - name: "desktop"
    bucket: "mocaccino-desktop"
    clean: false
    enabled: true
    project: "desktop" 
    qa: false
    branch: master
    arch: amd64
    buildkit: 0
    smart: false
    prune: false
    squash: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinoos/desktop-cache"
    tree: ""

  - name: "kernel-repo"
    bucket: "mocaccino-kernel"
    clean: false
    qa: true
    branch: master
    project: "kernel-repo" 
    enabled: true
    arch: amd64
    prune: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    buildkit: 0
    smart: false
    squash: false
    queue: lxd
    kube: false
    imageRepository: "quay.io/mocaccinocache/kernel-repo-amd64-cache"
    tree: ""

  - name: "portage-tree"
    bucket: "mocaccino-portage-tree"
    clean: true
    prune: false
    branch: master
    qa: true
    enabled: true
    arch: amd64
    project: "portage-tree" 
    buildkit: 0
    smart: false
    squash: false
    build_args: "--skip-if-metadata-exists=true --emoji=false --color=false --pull --only-target-package --push --plugin luetplugin-pkg-build-cleanup"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/portage-amd64-cache"
    tree: ""

  - name: "musl-universe"
    bucket: "mocaccino-musl-universe"
    clean: true
    branch: master
    qa: true
    prune: false
    arch: amd64
    project: "mocaccino-musl-universe" 
    buildkit: 0
    smart: false
    squash: false
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: false
    imageRepository: "quay.io/mocaccinocache/musl-universe-amd64-cache"
    tree: ""
    enabled: true

  - name: "mocaccino-aports"
    bucket: "mocaccino-aports"
    clean: true
    project: "mocaccino-aports" 
    branch: master
    qa: true
    arch: amd64
    buildkit: 0
    smart: false
    prune: false
    squash: true
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    queue: lxd_mocaccino
    kube: true
    tree: "/"
    imageRepository: "quay.io/mocaccinocache/aports-amd64-cache"
    enabled: true

  - name: "distfiles-collection"
    bucket: "mocaccino-distfiles-collection"
    clean: true
    qa: false
    branch: master
    project: "distfiles-collection" 
    arch: amd64
    prune: true
    build_args: "--skip-if-metadata-exists=true --no-spinner --emoji=false --color=false --pull --only-target-package --push"
    buildkit: 0
    smart: false
    tree: ""
    squash: false
    kube: false
    imageRepository: "quay.io/mocaccinocache/distfiles-amd64-cache"
    queue: lxd_mocaccino
    enabled: true

qa:
  chart: "https://github.com/mocaccinoOS/mocaccino-charty/releases/download/v0.2.9/package-smoke-0.2.3.tar.gz"
  from_repo: true
  repo: https://github.com/mocaccinoOS/mocaccino-charty
  path: testcharts/package-smoke
  luet_version: "0.9.2"
  bucket: mocaccino-qa
slack:
  channel: "mocaccino"
  enabled: true
