name: MocaccinoOS Micro

on:
  push:
    paths:
    - 'conf/**'
    - 'specs/**'
    - 'scripts/**'
    - '.github/workflows/**'
    branches: [ master, develop ]
  pull_request:
    paths:
    - 'conf/**'
    - 'specs/**'
    - 'scripts/**'
    - '.github/workflows/**'
    branches: [ master, develop ]
  schedule:
    - cron:  '* 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Install Luet and deps 🔧
      run: |
        sudo apt-get install -y xorriso squashfs-tools dosfstools
        curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
        sudo luet install repository/mocaccino-extra
        sudo luet install utils/jq utils/yq
    - name: ISO Build 🔧
      run: |
            sudo -E ./scripts/isospec specs/micro.yaml
            mkdir isobuild
            mv *.iso *.sha256 isobuild/
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1

    - name: Install minio and login
      env:
        MINIO_API_URL: ${{ secrets.MINIO_API_URL }}
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      run: |
        sudo wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/bin/mc
        sudo chmod +x /usr/bin/mc
        mc alias set minio $MINIO_API_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

    - name: Deploy 🚀
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        mc cp --recursive $PWD/isobuild/ minio/mocaccino-iso
